# Generated by Django 4.2.2 on 2023-07-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_populate_employees_quantity_ranges_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="house_number",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
