# Generated by Django 4.2.2 on 2023-07-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_address_house_number_alter_address_street"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="instagram",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="linkedin",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="twitter",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="web_site",
            field=models.URLField(null=True),
        ),
    ]
